### ISSUE TITLE
불필요한 파일을 삭제해주세요.

### ISSUE THREAD

**Issue by Shingiwon** [knut-cs/Curriculum#16]
## 이슈 타입을 체크해주세요.
- [x] feature
- [ ] hot-fix
- [ ] docs

## 이슈 내용
- 불필요한 파일을 삭제해주세요. (이미지, js)

**Comment by wjdrkfka3** [comment]
MD파일중에도 불필요한 파일이 있으니 함께 삭제하여 PR 부탁드립니다.
- CODE_OF_CONDUCT.md
- blueprint.md
